name: Publish docker image
on: 
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_PAT }}
          registry: docker.pkg.github.com
          repository: dlmousey/sarcasm-bot/sarcasm-bot
          tag_with_Ref: true
