on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install eslint to Action environment
        run: npm i -g eslint

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: eslint .
